<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.11.1 on win32)" generated="20230202 23:16:44.340" rpa="false" schemaversion="3">
<suite id="s1" name="TestSuite" source="C:\personal\fluxtest\tests\TestSuite.robot">
<test id="s1-t1" name="Login User with Password" line="9">
<kw name="Connect to Server" library="keywords">
<kw name="Connect">
<arg>fe80::aede:48ff:fe00:1122</arg>
<msg timestamp="20230202 23:16:44.369" level="FAIL">No keyword with name 'Connect' found.</msg>
<status status="FAIL" starttime="20230202 23:16:44.369" endtime="20230202 23:16:44.369"/>
</kw>
<status status="FAIL" starttime="20230202 23:16:44.368" endtime="20230202 23:16:44.369"/>
</kw>
<kw name="Login User" library="keywords">
<arg>ironman</arg>
<arg>1234567890</arg>
<status status="NOT RUN" starttime="20230202 23:16:44.370" endtime="20230202 23:16:44.370"/>
</kw>
<kw name="Verify Valid Login" library="keywords">
<arg>Tony Stark</arg>
<status status="NOT RUN" starttime="20230202 23:16:44.370" endtime="20230202 23:16:44.370"/>
</kw>
<kw name="Close Server Connection" library="keywords" type="TEARDOWN">
<kw name="Disconnect">
<msg timestamp="20230202 23:16:44.372" level="FAIL">No keyword with name 'Disconnect' found.</msg>
<status status="FAIL" starttime="20230202 23:16:44.371" endtime="20230202 23:16:44.372"/>
</kw>
<status status="FAIL" starttime="20230202 23:16:44.370" endtime="20230202 23:16:44.372">No keyword with name 'Disconnect' found.</status>
</kw>
<tag>positive</tag>
<status status="FAIL" starttime="20230202 23:16:44.368" endtime="20230202 23:16:44.372">No keyword with name 'Connect' found.

Also teardown failed:
No keyword with name 'Disconnect' found.</status>
</test>
<test id="s1-t2" name="Denied Login with Wrong Password" line="15">
<kw name="Connect to Server" library="keywords">
<kw name="Connect">
<arg>fe80::aede:48ff:fe00:1122</arg>
<msg timestamp="20230202 23:16:44.375" level="FAIL">No keyword with name 'Connect' found.</msg>
<status status="FAIL" starttime="20230202 23:16:44.375" endtime="20230202 23:16:44.375"/>
</kw>
<status status="FAIL" starttime="20230202 23:16:44.374" endtime="20230202 23:16:44.375"/>
</kw>
<kw name="Run Keyword And Expect Error" library="BuiltIn">
<arg>*Invalid Password</arg>
<arg>Login User</arg>
<arg>ironman</arg>
<arg>123</arg>
<doc>Runs the keyword and checks that the expected error occurred.</doc>
<status status="NOT RUN" starttime="20230202 23:16:44.375" endtime="20230202 23:16:44.375"/>
</kw>
<kw name="Verify Unauthorised Access" library="keywords">
<status status="NOT RUN" starttime="20230202 23:16:44.376" endtime="20230202 23:16:44.376"/>
</kw>
<kw name="Close Server Connection" library="keywords" type="TEARDOWN">
<kw name="Disconnect">
<msg timestamp="20230202 23:16:44.377" level="FAIL">No keyword with name 'Disconnect' found.</msg>
<status status="FAIL" starttime="20230202 23:16:44.377" endtime="20230202 23:16:44.377"/>
</kw>
<status status="FAIL" starttime="20230202 23:16:44.376" endtime="20230202 23:16:44.377">No keyword with name 'Disconnect' found.</status>
</kw>
<tag>negative</tag>
<status status="FAIL" starttime="20230202 23:16:44.373" endtime="20230202 23:16:44.377">No keyword with name 'Connect' found.

Also teardown failed:
No keyword with name 'Disconnect' found.</status>
</test>
<doc>A test suite for valid login.

Keywords are imported from the resource file</doc>
<status status="FAIL" starttime="20230202 23:16:44.341" endtime="20230202 23:16:44.378"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="2" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">negative</stat>
<stat pass="0" fail="1" skip="0">positive</stat>
</tag>
<suite>
<stat pass="0" fail="2" skip="0" id="s1" name="TestSuite">TestSuite</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230202 23:16:44.364" level="ERROR">Error in file 'C:\personal\fluxtest\tests\keywords.resource' on line 4: Importing library 'C:\personal\fluxtest\tests\CustomLibrary.py' failed: ModuleNotFoundError: No module named 'TestObject'
Traceback (most recent call last):
  File "C:\personal\fluxtest\tests\CustomLibrary.py", line 1, in &lt;module&gt;
    from TestObject import TestObject
PYTHONPATH:
  C:\personal\fluxtest\tests
  C:\Users\JonathanOpperman\.virtualenvs\fluxtest-eDvR_yxa\Scripts\robot.exe
  C:\Users\JonathanOpperman\AppData\Local\Programs\Python\Python311\python311.zip
  C:\Users\JonathanOpperman\AppData\Local\Programs\Python\Python311\DLLs
  C:\Users\JonathanOpperman\AppData\Local\Programs\Python\Python311\Lib
  C:\Users\JonathanOpperman\AppData\Local\Programs\Python\Python311
  C:\Users\JonathanOpperman\.virtualenvs\fluxtest-eDvR_yxa
  C:\Users\JonathanOpperman\.virtualenvs\fluxtest-eDvR_yxa\Lib\site-packages</msg>
</errors>
</robot>
